In [ ]:
!pip install sdmetrics

In [1]:
from sdmetrics.reports.single_table import QualityReport
import pandas as pd


import json

def load_config(json_path):
    with open(json_path, "r", encoding="utf-8") as f:
        return json.load(f)
    
def load_table(data_path):
    df = pd.read_csv(data_path)
    return df

In [3]:

def build_metadata_from_config(df, config, dataset='adult'):
    metadata = {
        "columns": {}
    }
    num_cols = set(config["num_col_idx"])
    cat_cols = set(config["cat_col_idx"])
    target_cols = set(config["target_col_idx"])

    for i, col in enumerate(df.columns):
        if i in num_cols:
            sdtype = "numerical"
        elif i in cat_cols:
            sdtype = "categorical"
        elif i in target_cols and dataset != 'beijing':
            sdtype = "categorical"
        elif i in target_cols and dataset == 'beijing':
            sdtype = "numerical"

        metadata["columns"][col] = {"sdtype": sdtype}

    return metadata

In [4]:
def calculate_quality_scores(real_df, pred_df, config, dataset='adult'):
    metadata = build_metadata_from_config(real_df, config, dataset)
    report = QualityReport()
    report.generate(real_df, pred_df, metadata)
    properties = report.get_properties().copy()

    column_shapes_score = properties.loc[
        properties["Property"] == "Column Shapes", "Score"
    ].iloc[0]

    column_pair_trends_score = properties.loc[
        properties["Property"] == "Column Pair Trends", "Score"
    ].iloc[0]

    overall_score = report.get_score()

    per_column_scores = report.get_details("Column Shapes").copy()
    per_column_scores = per_column_scores[["Column", "Score"]].rename(
        columns={"Score": "shape_score"}
    )

    pair_details = report.get_details("Column Pair Trends").copy()

    result = {
        "dataset": dataset,
        "column_shapes_score": column_shapes_score,
        "column_pair_trends_score": column_pair_trends_score,
        "overall_score": overall_score,
        "per_column_scores": per_column_scores,
        "pair_details": pair_details,
        "properties": properties,
        "report": report,
    }

    return result

In [ ]:
!ls

LICENSE       data          tabsyn        test.py
README.md     metrics.ipynb tadiff

In [31]:
!ls

LICENSE       data          tabcsdi       tadiff
README.md     metrics.ipynb tabsyn        test.py

# Adult

In [7]:
def calc(dataset):
    model_paths = {
        "tabcsdi": f"./tabcsdi/prediction_{dataset}.csv",
        "tabsyn": f"./tabsyn/prediction_{dataset}.csv",
        "tabdiff": f"./tabdiff/prediction_{dataset}.csv",
        "catboost": f"./catboost/prediction_{dataset}.csv"
    }
    print(len(model_paths))

    config = load_config(f"./data/{dataset}/info.json")
    real_df = load_table(f"./data/{dataset}/test.csv")

    all_results = {}
    summary_rows = []
    per_column_rows = []
    pair_rows = []

    for model_name, pred_path in model_paths.items():
        pred_df = load_table(pred_path)

        result = calculate_quality_scores(
            real_df=real_df,
            pred_df=pred_df,
            config=config,
            dataset=dataset
        )

        all_results[model_name] = result


        summary_rows.append({
            "dataset": dataset,
            "model": model_name,
            "Column Shapes Score": result["column_shapes_score"],
            "Column Pair Trends Score": result["column_pair_trends_score"],
            "Overall Score": result["overall_score"],
        })

        tmp_col = result["per_column_scores"].copy()
        tmp_col["dataset"] =dataset
        tmp_col["model"] = model_name
        per_column_rows.append(tmp_col)

        tmp_pair = result["pair_details"].copy()
        tmp_pair["dataset"] = dataset
        tmp_pair["model"] = model_name
        pair_rows.append(tmp_pair)
    return summary_rows, per_column_rows, pair_rows

In [8]:
summary_rows, per_column_rows, pair_rows = calc('adult')
summary_df = pd.DataFrame(summary_rows)
per_column_df = pd.concat(per_column_rows, ignore_index=True)
pair_df = pd.concat(pair_rows, ignore_index=True)

4
Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 15/15 [00:00<00:00, 229.27it/s]|
Column Shapes Score: 84.16%

(2/2) Evaluating Column Pair Trends: |██████████| 105/105 [00:00<00:00, 464.17it/s]|
Column Pair Trends Score: 87.13%

Overall Score (Average): 85.65%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 15/15 [00:00<00:00, 230.86it/s]|
Column Shapes Score: 96.97%

(2/2) Evaluating Column Pair Trends: |██████████| 105/105 [00:00<00:00, 476.86it/s]|
Column Pair Trends Score: 90.17%

Overall Score (Average): 93.57%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 15/15 [00:00<00:00, 279.71it/s]|
Column Shapes Score: 98.9%

(2/2) Evaluating Column Pair Trends: |██████████| 105/105 [00:00<00:00, 472.77it/s]|
Column Pair Trends Score: 85.83%

Overall Score (Average): 92.36%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 15/15 [00:00<00:00, 191.70it/s]|
Column Shapes Score: 73.54%

(2/2) Evaluating Column Pair Trends: |██████████| 105/105 [00:00<00:00, 386.85it/s]|
Column Pair Trends Score: 75.04%

Overall Score (Average): 74.29%

In [9]:
summary_df

,dataset,model,Column Shapes Score,Column Pair Trends Score,Overall Score
0,adult,tabcsdi,0.841599,0.871332,0.856465
1,adult,tabsyn,0.969654,0.901698,0.935676
2,adult,tabdiff,0.988981,0.858311,0.923646
3,adult,catboost,0.735360,0.750426,0.742893

In [10]:
per_column_df

            Column  shape_score dataset     model
0              age     0.944414   adult   tabcsdi
1        workclass     0.993735   adult   tabcsdi
2           fnlwgt     0.947485   adult   tabcsdi
3        education     0.983416   adult   tabcsdi
4    education.num     0.752779   adult   tabcsdi
5   marital.status     0.981021   adult   tabcsdi
6       occupation     0.942878   adult   tabcsdi
7     relationship     0.972852   adult   tabcsdi
8             race     0.992629   adult   tabcsdi
9              sex     0.998280   adult   tabcsdi
10    capital.gain     0.291444   adult   tabcsdi
11    capital.loss     0.147657   adult   tabcsdi
12  hours.per.week     0.711259   adult   tabcsdi
13  native.country     0.979117   adult   tabcsdi
14          income     0.985013   adult   tabcsdi
15             age     0.953873   adult    tabsyn
16       workclass     0.958234   adult    tabsyn
17          fnlwgt     0.939254   adult    tabsyn
18       education     0.928628   adult    tabsyn
19   education.num     0.995701   adult    tabsyn
20  marital.status     0.986794   adult    tabsyn
21      occupation     0.963393   adult    tabsyn
22    relationship     0.962594   adult    tabsyn
23            race     0.979424   adult    tabsyn
24             sex     0.996130   adult    tabsyn
25    capital.gain     0.981267   adult    tabsyn
26    capital.loss     0.987593   adult    tabsyn
27  hours.per.week     0.958049   adult    tabsyn
28  native.country     0.968675   adult    tabsyn
29          income     0.985197   adult    tabsyn
30             age     0.972483   adult   tabdiff
31       workclass     0.984890   adult   tabdiff
32          fnlwgt     0.984890   adult   tabdiff
33       education     0.987409   adult   tabdiff
34   education.num     0.986119   adult   tabdiff
35  marital.status     0.991647   adult   tabdiff
36      occupation     0.985382   adult   tabdiff
37    relationship     0.994349   adult   tabdiff
38            race     0.992015   adult   tabdiff
39             sex     0.996438   adult   tabdiff
40    capital.gain     0.988821   adult   tabdiff
41    capital.loss     0.995209   adult   tabdiff
42  hours.per.week     0.983908   adult   tabdiff
43  native.country     0.992384   adult   tabdiff
44          income     0.998772   adult   tabdiff
45             age     0.818684   adult  catboost
46       workclass     0.723420   adult  catboost
47          fnlwgt     0.601192   adult  catboost
48       education     1.000000   adult  catboost
49   education.num     0.758184   adult  catboost
50  marital.status     0.940667   adult  catboost
51      occupation     0.643757   adult  catboost
52    relationship     0.930348   adult  catboost
53            race     0.883975   adult  catboost
54             sex     0.999386   adult  catboost
55    capital.gain     0.103556   adult  catboost
56    capital.loss     0.072907   adult  catboost
57  hours.per.week     0.689945   adult  catboost
58  native.country     0.919968   adult  catboost
59          income     0.944414   adult  catboost

In [11]:
pair_df.dropna(subset=["Score"])

,Column 1,Column 2,Metric,Score,Real Correlation,Synthetic Correlation,Real Association,Meets Threshold?,dataset,model
13,age,income,ContingencySimilarity,0.938763,NaN,NaN,0.315142,True,adult,tabcsdi
18,workclass,occupation,ContingencySimilarity,0.861925,NaN,NaN,0.400611,True,adult,tabcsdi
39,education,education.num,ContingencySimilarity,0.564462,NaN,NaN,1.000000,True,adult,tabcsdi
49,education,income,ContingencySimilarity,0.968307,NaN,NaN,0.360356,True,adult,tabcsdi
59,education.num,income,ContingencySimilarity,0.587925,NaN,NaN,0.354417,True,adult,tabcsdi
61,marital.status,relationship,ContingencySimilarity,0.894233,NaN,NaN,0.488974,True,adult,tabcsdi
63,marital.status,sex,ContingencySimilarity,0.962902,NaN,NaN,0.455158,True,adult,tabcsdi
68,marital.status,income,ContingencySimilarity,0.960997,NaN,NaN,0.450240,True,adult,tabcsdi
71,occupation,sex,ContingencySimilarity,0.871445,NaN,NaN,0.424559,True,adult,tabcsdi
76,occupation,income,ContingencySimilarity,0.910939,NaN,NaN,0.347587,True,adult,tabcsdi
78,relationship,sex,ContingencySimilarity,0.911308,NaN,NaN,0.641880,True,adult,tabcsdi
83,relationship,income,ContingencySimilarity,0.960506,NaN,NaN,0.456393,True,adult,tabcsdi
88,race,native.country,ContingencySimilarity,0.933604,NaN,NaN,0.393413,True,adult,tabcsdi
118,age,income,ContingencySimilarity,0.932498,NaN,NaN,0.315142,True,adult,tabsyn
123,workclass,occupation,ContingencySimilarity,0.878816,NaN,NaN,0.400611,True,adult,tabsyn
144,education,education.num,ContingencySimilarity,0.447024,NaN,NaN,1.000000,True,adult,tabsyn
154,education,income,ContingencySimilarity,0.913642,NaN,NaN,0.360356,True,adult,tabsyn
164,education.num,income,ContingencySimilarity,0.980100,NaN,NaN,0.354417,True,adult,tabsyn
166,marital.status,relationship,ContingencySimilarity,0.927707,NaN,NaN,0.488974,True,adult,tabsyn
168,marital.status,sex,ContingencySimilarity,0.975800,NaN,NaN,0.455158,True,adult,tabsyn
173,marital.status,income,ContingencySimilarity,0.974633,NaN,NaN,0.450240,True,adult,tabsyn
176,occupation,sex,ContingencySimilarity,0.917143,NaN,NaN,0.424559,True,adult,tabsyn
181,occupation,income,ContingencySimilarity,0.947362,NaN,NaN,0.347587,True,adult,tabsyn
183,relationship,sex,ContingencySimilarity,0.933051,NaN,NaN,0.641880,True,adult,tabsyn
188,relationship,income,ContingencySimilarity,0.951354,NaN,NaN,0.456393,True,adult,tabsyn
193,race,native.country,ContingencySimilarity,0.942940,NaN,NaN,0.393413,True,adult,tabsyn
223,age,income,ContingencySimilarity,0.921074,NaN,NaN,0.315142,True,adult,tabdiff
228,workclass,occupation,ContingencySimilarity,0.827160,NaN,NaN,0.400611,True,adult,tabdiff
249,education,education.num,ContingencySimilarity,0.569375,NaN,NaN,1.000000,True,adult,tabdiff
259,education,income,ContingencySimilarity,0.933972,NaN,NaN,0.360356,True,adult,tabdiff
269,education.num,income,ContingencySimilarity,0.957496,NaN,NaN,0.354417,True,adult,tabdiff
271,marital.status,relationship,ContingencySimilarity,0.655979,NaN,NaN,0.488974,True,adult,tabdiff
273,marital.status,sex,ContingencySimilarity,0.897856,NaN,NaN,0.455158,True,adult,tabdiff
278,marital.status,income,ContingencySimilarity,0.893987,NaN,NaN,0.450240,True,adult,tabdiff
281,occupation,sex,ContingencySimilarity,0.881948,NaN,NaN,0.424559,True,adult,tabdiff
286,occupation,income,ContingencySimilarity,0.927707,NaN,NaN,0.347587,True,adult,tabdiff
288,relationship,sex,ContingencySimilarity,0.845894,NaN,NaN,0.641880,True,adult,tabdiff
293,relationship,income,ContingencySimilarity,0.892943,NaN,NaN,0.456393,True,adult,tabdiff
298,race,native.country,ContingencySimilarity,0.952644,NaN,NaN,0.393413,True,adult,tabdiff
328,age,income,ContingencySimilarity,0.671703,NaN,NaN,0.315142,True,adult,catboost
333,workclass,occupation,ContingencySimilarity,0.485597,NaN,NaN,0.400611,True,adult,catboost
354,education,education.num,ContingencySimilarity,0.547018,NaN,NaN,1.000000,True,adult,catboost
364,education,income,ContingencySimilarity,0.928813,NaN,NaN,0.360356,True,adult,catboost
374,education.num,income,ContingencySimilarity,0.540569,NaN,NaN,0.354417,True,adult,catboost
376,marital.status,relationship,ContingencySimilarity,0.894540,NaN,NaN,0.488974,True,adult,catboost
378,marital.status,sex,ContingencySimilarity,0.940667,NaN,NaN,0.455158,True,adult,catboost
383,marital.status,income,ContingencySimilarity,0.897918,NaN,NaN,0.450240,True,adult,catboost
386,occupation,sex,ContingencySimilarity,0.614950,NaN,NaN,0.424559,True,adult,catboost
391,occupation,income,ContingencySimilarity,0.603587,NaN,NaN,0.347587,True,adult,catboost
393,relationship,sex,ContingencySimilarity,0.927461,NaN,NaN,0.641880,True,adult,catboost
398,relationship,income,ContingencySimilarity,0.882747,NaN,NaN,0.456393,True,adult,catboost
403,race,native.country,ContingencySimilarity,0.819974,NaN,NaN,0.393413,True,adult,catboost

# Magic

In [12]:
summary_rows, per_column_rows, pair_rows = calc('magic')
summary_df = pd.DataFrame(summary_rows)
per_column_df = pd.concat(per_column_rows, ignore_index=True)
pair_df = pd.concat(pair_rows, ignore_index=True)

4
Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 11/11 [00:00<00:00, 540.09it/s]|
Column Shapes Score: 96.11%

(2/2) Evaluating Column Pair Trends: |██████████| 55/55 [00:00<00:00, 730.77it/s]|
Column Pair Trends Score: 95.12%

Overall Score (Average): 95.62%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 11/11 [00:00<00:00, 1057.52it/s]|
Column Shapes Score: 97.16%

(2/2) Evaluating Column Pair Trends: |██████████| 55/55 [00:00<00:00, 907.88it/s]|
Column Pair Trends Score: 94.91%

Overall Score (Average): 96.04%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 11/11 [00:00<00:00, 1087.91it/s]|
Column Shapes Score: 95.86%

(2/2) Evaluating Column Pair Trends: |██████████| 55/55 [00:00<00:00, 669.79it/s]|
Column Pair Trends Score: 92.46%

Overall Score (Average): 94.16%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 11/11 [00:00<00:00, 1030.33it/s]|
Column Shapes Score: 84.35%

(2/2) Evaluating Column Pair Trends: |██████████| 55/55 [00:00<00:00, 803.15it/s]|
Column Pair Trends Score: 92.0%

Overall Score (Average): 88.17%

In [13]:
summary_df

,dataset,model,Column Shapes Score,Column Pair Trends Score,Overall Score
0,magic,tabcsdi,0.961141,0.951245,0.956193
1,magic,tabsyn,0.971561,0.949142,0.960352
2,magic,tabdiff,0.958608,0.924589,0.941598
3,magic,catboost,0.843466,0.920012,0.881739

In [14]:
per_column_df

     Column  shape_score dataset     model
0    Length     0.973712   magic   tabcsdi
1     Width     0.958465   magic   tabcsdi
2      Size     0.981073   magic   tabcsdi
3      Conc     0.984227   magic   tabcsdi
4     Conc1     0.986330   magic   tabcsdi
5      Asym     0.923239   magic   tabcsdi
6    M3Long     0.943218   magic   tabcsdi
7   M3Trans     0.911672   magic   tabcsdi
8     Alpha     0.964774   magic   tabcsdi
9      Dist     0.967403   magic   tabcsdi
10    class     0.978444   magic   tabcsdi
11   Length     0.967403   magic    tabsyn
12    Width     0.963722   magic    tabsyn
13     Size     0.971083   magic    tabsyn
14     Conc     0.981598   magic    tabsyn
15    Conc1     0.978444   magic    tabsyn
16     Asym     0.971609   magic    tabsyn
17   M3Long     0.962671   magic    tabsyn
18  M3Trans     0.976341   magic    tabsyn
19    Alpha     0.969506   magic    tabsyn
20     Dist     0.954784   magic    tabsyn
21    class     0.990011   magic    tabsyn
22   Length     0.935857   magic   tabdiff
23    Width     0.945846   magic   tabdiff
24     Size     0.937960   magic   tabdiff
25     Conc     0.949001   magic   tabdiff
26    Conc1     0.987907   magic   tabdiff
27     Asym     0.958465   magic   tabdiff
28   M3Long     0.953733   magic   tabdiff
29  M3Trans     0.969506   magic   tabdiff
30    Alpha     0.949527   magic   tabdiff
31     Dist     0.959516   magic   tabdiff
32    class     0.997371   magic   tabdiff
33   Length     0.915352   magic  catboost
34    Width     0.929022   magic  catboost
35     Size     0.960568   magic  catboost
36     Conc     0.988433   magic  catboost
37    Conc1     0.983701   magic  catboost
38     Asym     0.722923   magic  catboost
39   M3Long     0.792324   magic  catboost
40  M3Trans     0.493691   magic  catboost
41    Alpha     0.799159   magic  catboost
42     Dist     0.751314   magic  catboost
43    class     0.941640   magic  catboost

In [15]:
pair_df.dropna(subset=["Score"])

,Column 1,Column 2,Metric,Score,Real Correlation,Synthetic Correlation,Real Association,Meets Threshold?,dataset,model
0,Length,Width,CorrelationSimilarity,0.981540,0.752390,0.789309,NaN,True,magic,tabcsdi
1,Length,Size,CorrelationSimilarity,0.996430,0.698769,0.705908,NaN,True,magic,tabcsdi
2,Length,Conc,CorrelationSimilarity,0.994738,-0.625760,-0.636283,NaN,True,magic,tabcsdi
3,Length,Conc1,CorrelationSimilarity,0.984604,-0.588086,-0.618877,NaN,True,magic,tabcsdi
9,Length,class,ContingencySimilarity,0.941640,NaN,NaN,0.358254,True,magic,tabcsdi
10,Width,Size,CorrelationSimilarity,0.995318,0.684998,0.694362,NaN,True,magic,tabcsdi
11,Width,Conc,CorrelationSimilarity,0.994299,-0.584398,-0.595799,NaN,True,magic,tabcsdi
12,Width,Conc1,CorrelationSimilarity,0.984764,-0.555381,-0.585853,NaN,True,magic,tabcsdi
18,Width,class,ContingencySimilarity,0.869085,NaN,NaN,0.335960,True,magic,tabcsdi
19,Size,Conc,CorrelationSimilarity,0.999536,-0.854080,-0.853152,NaN,True,magic,tabcsdi
20,Size,Conc1,CorrelationSimilarity,0.981067,-0.811145,-0.849012,NaN,True,magic,tabcsdi
27,Conc,Conc1,CorrelationSimilarity,0.996617,0.975419,0.968654,NaN,True,magic,tabcsdi
48,M3Long,class,ContingencySimilarity,0.712408,NaN,NaN,0.380717,True,magic,tabcsdi
53,Alpha,class,ContingencySimilarity,0.885384,NaN,NaN,0.485377,True,magic,tabcsdi
55,Length,Width,CorrelationSimilarity,0.986152,0.752390,0.780086,NaN,True,magic,tabsyn
56,Length,Size,CorrelationSimilarity,0.990340,0.698769,0.718089,NaN,True,magic,tabsyn
57,Length,Conc,CorrelationSimilarity,0.998453,-0.625760,-0.622667,NaN,True,magic,tabsyn
58,Length,Conc1,CorrelationSimilarity,0.990228,-0.588086,-0.607629,NaN,True,magic,tabsyn
64,Length,class,ContingencySimilarity,0.898528,NaN,NaN,0.358254,True,magic,tabsyn
65,Width,Size,CorrelationSimilarity,0.987208,0.684998,0.710581,NaN,True,magic,tabsyn
66,Width,Conc,CorrelationSimilarity,0.999837,-0.584398,-0.584723,NaN,True,magic,tabsyn
67,Width,Conc1,CorrelationSimilarity,0.988853,-0.555381,-0.577674,NaN,True,magic,tabsyn
73,Width,class,ContingencySimilarity,0.895899,NaN,NaN,0.335960,True,magic,tabsyn
74,Size,Conc,CorrelationSimilarity,0.998454,-0.854080,-0.850989,NaN,True,magic,tabsyn
75,Size,Conc1,CorrelationSimilarity,0.986862,-0.811145,-0.837420,NaN,True,magic,tabsyn
82,Conc,Conc1,CorrelationSimilarity,0.995145,0.975419,0.965710,NaN,True,magic,tabsyn
103,M3Long,class,ContingencySimilarity,0.766036,NaN,NaN,0.380717,True,magic,tabsyn
108,Alpha,class,ContingencySimilarity,0.805994,NaN,NaN,0.485377,True,magic,tabsyn
110,Length,Width,CorrelationSimilarity,0.994134,0.752390,0.740659,NaN,True,magic,tabdiff
111,Length,Size,CorrelationSimilarity,0.999679,0.698769,0.698126,NaN,True,magic,tabdiff
112,Length,Conc,CorrelationSimilarity,0.993282,-0.625760,-0.639196,NaN,True,magic,tabdiff
113,Length,Conc1,CorrelationSimilarity,0.985009,-0.588086,-0.618068,NaN,True,magic,tabdiff
119,Length,class,ContingencySimilarity,0.895899,NaN,NaN,0.358254,True,magic,tabdiff
120,Width,Size,CorrelationSimilarity,0.991517,0.684998,0.668031,NaN,True,magic,tabdiff
121,Width,Conc,CorrelationSimilarity,0.995172,-0.584398,-0.574742,NaN,True,magic,tabdiff
122,Width,Conc1,CorrelationSimilarity,0.993752,-0.555381,-0.567877,NaN,True,magic,tabdiff
128,Width,class,ContingencySimilarity,0.569401,NaN,NaN,0.335960,True,magic,tabdiff
129,Size,Conc,CorrelationSimilarity,0.946034,-0.854080,-0.746148,NaN,True,magic,tabdiff
130,Size,Conc1,CorrelationSimilarity,0.978066,-0.811145,-0.767276,NaN,True,magic,tabdiff
137,Conc,Conc1,CorrelationSimilarity,0.940891,0.975419,0.857201,NaN,True,magic,tabdiff
158,M3Long,class,ContingencySimilarity,0.837014,NaN,NaN,0.380717,True,magic,tabdiff
163,Alpha,class,ContingencySimilarity,0.824395,NaN,NaN,0.485377,True,magic,tabdiff
165,Length,Width,CorrelationSimilarity,0.944375,0.752390,0.863641,NaN,True,magic,catboost
166,Length,Size,CorrelationSimilarity,0.967256,0.698769,0.764257,NaN,True,magic,catboost
167,Length,Conc,CorrelationSimilarity,0.986833,-0.625760,-0.652094,NaN,True,magic,catboost
168,Length,Conc1,CorrelationSimilarity,0.975281,-0.588086,-0.637523,NaN,True,magic,catboost
174,Length,class,ContingencySimilarity,0.866456,NaN,NaN,0.358254,True,magic,catboost
175,Width,Size,CorrelationSimilarity,0.949061,0.684998,0.786876,NaN,True,magic,catboost
176,Width,Conc,CorrelationSimilarity,0.967628,-0.584398,-0.649141,NaN,True,magic,catboost
177,Width,Conc1,CorrelationSimilarity,0.960207,-0.555381,-0.634967,NaN,True,magic,catboost
183,Width,class,ContingencySimilarity,0.848055,NaN,NaN,0.335960,True,magic,catboost
184,Size,Conc,CorrelationSimilarity,0.976567,-0.854080,-0.900946,NaN,True,magic,catboost
185,Size,Conc1,CorrelationSimilarity,0.960116,-0.811145,-0.890913,NaN,True,magic,catboost
192,Conc,Conc1,CorrelationSimilarity,0.994635,0.975419,0.986149,NaN,True,magic,catboost
213,M3Long,class,ContingencySimilarity,0.865405,NaN,NaN,0.380717,True,magic,catboost
218,Alpha,class,ContingencySimilarity,0.618297,NaN,NaN,0.485377,True,magic,catboost

# Shoppers

In [16]:
summary_rows, per_column_rows, pair_rows = calc('shoppers')
summary_df = pd.DataFrame(summary_rows)
per_column_df = pd.concat(per_column_rows, ignore_index=True)
pair_df = pd.concat(pair_rows, ignore_index=True)

4
Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 18/18 [00:00<00:00, 1349.11it/s]|
Column Shapes Score: 76.23%

(2/2) Evaluating Column Pair Trends: |██████████| 153/153 [00:00<00:00, 974.43it/s]|
Column Pair Trends Score: 89.22%

Overall Score (Average): 82.73%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 18/18 [00:00<00:00, 2159.85it/s]|
Column Shapes Score: 95.67%

(2/2) Evaluating Column Pair Trends: |██████████| 153/153 [00:00<00:00, 1334.34it/s]|
Column Pair Trends Score: 90.19%

Overall Score (Average): 92.93%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 18/18 [00:00<00:00, 2215.17it/s]|
Column Shapes Score: 95.46%

(2/2) Evaluating Column Pair Trends: |██████████| 153/153 [00:00<00:00, 1342.69it/s]|
Column Pair Trends Score: 85.75%

Overall Score (Average): 90.61%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 18/18 [00:00<00:00, 2025.42it/s]|
Column Shapes Score: 65.12%

(2/2) Evaluating Column Pair Trends: |██████████| 153/153 [00:00<00:00, 1309.16it/s]|
Column Pair Trends Score: 81.8%

Overall Score (Average): 73.46%

In [17]:
summary_df

,dataset,model,Column Shapes Score,Column Pair Trends Score,Overall Score
0,shoppers,tabcsdi,0.762323,0.892222,0.827273
1,shoppers,tabsyn,0.956655,0.901875,0.929265
2,shoppers,tabdiff,0.954627,0.857503,0.906065
3,shoppers,catboost,0.651167,0.818015,0.734591

In [18]:
per_column_df

                     Column  shape_score   dataset     model
0            Administrative     0.579075  shoppers   tabcsdi
1   Administrative_Duration     0.682887  shoppers   tabcsdi
2             Informational     0.328467  shoppers   tabcsdi
3    Informational_Duration     0.243309  shoppers   tabcsdi
4            ProductRelated     0.909165  shoppers   tabcsdi
..                      ...          ...       ...       ...
67                   Region     0.397405  shoppers  catboost
68              TrafficType     0.733982  shoppers  catboost
69              VisitorType     0.927818  shoppers  catboost
70                  Weekend     0.768856  shoppers  catboost
71                  Revenue     0.977291  shoppers  catboost

[72 rows x 4 columns]

In [19]:
pair_df.dropna(subset=["Score"])

,Column 1,Column 2,Metric,Score,Real Correlation,Synthetic Correlation,Real Association,Meets Threshold?,dataset,model
0,Administrative,Administrative_Duration,CorrelationSimilarity,0.960437,0.593842,0.514716,NaN,True,shoppers,tabcsdi
33,Informational,Informational_Duration,CorrelationSimilarity,0.882085,0.687845,0.452014,NaN,True,shoppers,tabcsdi
62,ProductRelated,ProductRelated_Duration,CorrelationSimilarity,0.888710,0.883052,0.660472,NaN,True,shoppers,tabcsdi
87,BounceRates,ExitRates,CorrelationSimilarity,0.989136,0.918279,0.896552,NaN,True,shoppers,tabcsdi
116,PageValues,Revenue,ContingencySimilarity,0.885645,NaN,NaN,0.552291,True,shoppers,tabcsdi
132,OperatingSystems,Browser,ContingencySimilarity,0.783455,NaN,NaN,0.616624,True,shoppers,tabcsdi
134,OperatingSystems,TrafficType,ContingencySimilarity,0.846715,NaN,NaN,0.354013,True,shoppers,tabcsdi
135,OperatingSystems,VisitorType,ContingencySimilarity,0.916464,NaN,NaN,0.386113,True,shoppers,tabcsdi
139,Browser,TrafficType,ContingencySimilarity,0.840227,NaN,NaN,0.326741,True,shoppers,tabcsdi
140,Browser,VisitorType,ContingencySimilarity,0.940795,NaN,NaN,0.498952,True,shoppers,tabcsdi
147,TrafficType,VisitorType,ContingencySimilarity,0.880779,NaN,NaN,0.397480,True,shoppers,tabcsdi
153,Administrative,Administrative_Duration,CorrelationSimilarity,0.945906,0.593842,0.485654,NaN,True,shoppers,tabsyn
186,Informational,Informational_Duration,CorrelationSimilarity,0.879131,0.687845,0.446107,NaN,True,shoppers,tabsyn
215,ProductRelated,ProductRelated_Duration,CorrelationSimilarity,0.912281,0.883052,0.707613,NaN,True,shoppers,tabsyn
240,BounceRates,ExitRates,CorrelationSimilarity,0.911612,0.918279,0.741503,NaN,True,shoppers,tabsyn
269,PageValues,Revenue,ContingencySimilarity,0.935118,NaN,NaN,0.552291,True,shoppers,tabsyn
285,OperatingSystems,Browser,ContingencySimilarity,0.820762,NaN,NaN,0.616624,True,shoppers,tabsyn
287,OperatingSystems,TrafficType,ContingencySimilarity,0.884023,NaN,NaN,0.354013,True,shoppers,tabsyn
288,OperatingSystems,VisitorType,ContingencySimilarity,0.939984,NaN,NaN,0.386113,True,shoppers,tabsyn
292,Browser,TrafficType,ContingencySimilarity,0.847526,NaN,NaN,0.326741,True,shoppers,tabsyn
293,Browser,VisitorType,ContingencySimilarity,0.941606,NaN,NaN,0.498952,True,shoppers,tabsyn
300,TrafficType,VisitorType,ContingencySimilarity,0.902676,NaN,NaN,0.397480,True,shoppers,tabsyn
306,Administrative,Administrative_Duration,CorrelationSimilarity,0.820239,0.593842,0.234321,NaN,True,shoppers,tabdiff
339,Informational,Informational_Duration,CorrelationSimilarity,0.783734,0.687845,0.255313,NaN,True,shoppers,tabdiff
368,ProductRelated,ProductRelated_Duration,CorrelationSimilarity,0.726635,0.883052,0.336321,NaN,True,shoppers,tabdiff
393,BounceRates,ExitRates,CorrelationSimilarity,0.874837,0.918279,0.667952,NaN,True,shoppers,tabdiff
422,PageValues,Revenue,ContingencySimilarity,0.897810,NaN,NaN,0.552291,True,shoppers,tabdiff
438,OperatingSystems,Browser,ContingencySimilarity,0.740470,NaN,NaN,0.616624,True,shoppers,tabdiff
440,OperatingSystems,TrafficType,ContingencySimilarity,0.899432,NaN,NaN,0.354013,True,shoppers,tabdiff
441,OperatingSystems,VisitorType,ContingencySimilarity,0.961071,NaN,NaN,0.386113,True,shoppers,tabdiff
445,Browser,TrafficType,ContingencySimilarity,0.866991,NaN,NaN,0.326741,True,shoppers,tabdiff
446,Browser,VisitorType,ContingencySimilarity,0.960260,NaN,NaN,0.498952,True,shoppers,tabdiff
453,TrafficType,VisitorType,ContingencySimilarity,0.901054,NaN,NaN,0.397480,True,shoppers,tabdiff
459,Administrative,Administrative_Duration,CorrelationSimilarity,0.866131,0.593842,0.861580,NaN,True,shoppers,catboost
492,Informational,Informational_Duration,CorrelationSimilarity,0.903184,0.687845,0.881477,NaN,True,shoppers,catboost
521,ProductRelated,ProductRelated_Duration,CorrelationSimilarity,0.998958,0.883052,0.880969,NaN,True,shoppers,catboost
546,BounceRates,ExitRates,CorrelationSimilarity,0.991453,0.918279,0.935373,NaN,True,shoppers,catboost
575,PageValues,Revenue,ContingencySimilarity,0.898621,NaN,NaN,0.552291,True,shoppers,catboost
591,OperatingSystems,Browser,ContingencySimilarity,0.699919,NaN,NaN,0.616624,True,shoppers,catboost
593,OperatingSystems,TrafficType,ContingencySimilarity,0.667478,NaN,NaN,0.354013,True,shoppers,catboost
594,OperatingSystems,VisitorType,ContingencySimilarity,0.799676,NaN,NaN,0.386113,True,shoppers,catboost
598,Browser,TrafficType,ContingencySimilarity,0.651257,NaN,NaN,0.326741,True,shoppers,catboost
599,Browser,VisitorType,ContingencySimilarity,0.806164,NaN,NaN,0.498952,True,shoppers,catboost
606,TrafficType,VisitorType,ContingencySimilarity,0.715328,NaN,NaN,0.397480,True,shoppers,catboost

# Default

In [20]:
summary_rows, per_column_rows, pair_rows = calc('default')
summary_df = pd.DataFrame(summary_rows)
per_column_df = pd.concat(per_column_rows, ignore_index=True)
pair_df = pd.concat(pair_rows, ignore_index=True)

4
Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 24/24 [00:00<00:00, 721.35it/s]|
Column Shapes Score: 90.52%

(2/2) Evaluating Column Pair Trends: |██████████| 276/276 [00:00<00:00, 1179.30it/s]|
Column Pair Trends Score: 93.59%

Overall Score (Average): 92.05%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 24/24 [00:00<00:00, 1026.61it/s]|
Column Shapes Score: 98.09%

(2/2) Evaluating Column Pair Trends: |██████████| 276/276 [00:00<00:00, 1227.24it/s]|
Column Pair Trends Score: 97.64%

Overall Score (Average): 97.87%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 24/24 [00:00<00:00, 949.45it/s]|
Column Shapes Score: 97.57%

(2/2) Evaluating Column Pair Trends: |██████████| 276/276 [00:00<00:00, 1100.50it/s]|
Column Pair Trends Score: 91.7%

Overall Score (Average): 94.63%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 24/24 [00:00<00:00, 540.70it/s]|
Column Shapes Score: 83.76%

(2/2) Evaluating Column Pair Trends: |██████████| 276/276 [00:00<00:00, 1184.54it/s]|
Column Pair Trends Score: 95.4%

Overall Score (Average): 89.58%

In [21]:
summary_df

,dataset,model,Column Shapes Score,Column Pair Trends Score,Overall Score
0,default,tabcsdi,0.905153,0.935870,0.920512
1,default,tabsyn,0.980903,0.976423,0.978663
2,default,tabdiff,0.975708,0.916990,0.946349
3,default,catboost,0.837597,0.953961,0.895779

In [22]:
pair_df

,Column 1,Column 2,Metric,Score,Real Correlation,Synthetic Correlation,Real Association,Meets Threshold?,dataset,model
0,LIMIT_BAL,SEX,ContingencySimilarity,NaN,NaN,NaN,0.099949,False,default,tabcsdi
1,LIMIT_BAL,EDUCATION,ContingencySimilarity,NaN,NaN,NaN,0.135725,False,default,tabcsdi
2,LIMIT_BAL,MARRIAGE,ContingencySimilarity,NaN,NaN,NaN,0.080955,False,default,tabcsdi
3,LIMIT_BAL,AGE,CorrelationSimilarity,NaN,0.137718,NaN,NaN,False,default,tabcsdi
4,LIMIT_BAL,PAY_0,ContingencySimilarity,NaN,NaN,NaN,0.111955,False,default,tabcsdi
...,...,...,...,...,...,...,...,...,...,...
1099,PAY_AMT4,PAY_AMT6,CorrelationSimilarity,NaN,0.284112,NaN,NaN,False,default,catboost
1100,PAY_AMT4,default payment next month,ContingencySimilarity,NaN,NaN,NaN,0.049440,False,default,catboost
1101,PAY_AMT5,PAY_AMT6,CorrelationSimilarity,NaN,0.231412,NaN,NaN,False,default,catboost
1102,PAY_AMT5,default payment next month,ContingencySimilarity,NaN,NaN,NaN,0.047362,False,default,catboost
1103,PAY_AMT6,default payment next month,ContingencySimilarity,NaN,NaN,NaN,0.038064,False,default,catboost

# Beijing

In [23]:
summary_rows, per_column_rows, pair_rows = calc('beijing')
summary_df = pd.DataFrame(summary_rows)
per_column_df = pd.concat(per_column_rows, ignore_index=True)
pair_df = pd.concat(pair_rows, ignore_index=True)

4
Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 12/12 [00:00<00:00, 478.83it/s]|
Column Shapes Score: 56.98%

(2/2) Evaluating Column Pair Trends: |██████████| 66/66 [00:00<00:00, 937.15it/s]|
Column Pair Trends Score: 52.22%

Overall Score (Average): 54.6%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 12/12 [00:00<00:00, 563.86it/s]|
Column Shapes Score: 95.85%

/opt/anaconda3/lib/python3.12/site-packages/scipy/stats/_axis_nan_policy.py:531: RuntimeWarning: ks_2samp: Exact calculation unsuccessful. Switching to method=asymp.
  res = hypotest_fun_out(*samples, **kwds)

(2/2) Evaluating Column Pair Trends: |██████████| 66/66 [00:00<00:00, 927.27it/s]|
Column Pair Trends Score: 90.82%

Overall Score (Average): 93.34%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 12/12 [00:00<00:00, 772.36it/s]|
Column Shapes Score: 96.21%

(2/2) Evaluating Column Pair Trends: |██████████| 66/66 [00:00<00:00, 1007.36it/s]|
Column Pair Trends Score: 86.2%

Overall Score (Average): 91.21%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 12/12 [00:00<00:00, 684.78it/s]|
Column Shapes Score: 77.56%

(2/2) Evaluating Column Pair Trends: |██████████| 66/66 [00:00<00:00, 1014.14it/s]|
Column Pair Trends Score: 82.92%

Overall Score (Average): 80.24%

In [24]:
summary_df

,dataset,model,Column Shapes Score,Column Pair Trends Score,Overall Score
0,beijing,tabcsdi,0.569824,0.522207,0.546015
1,beijing,tabsyn,0.958493,0.908235,0.933364
2,beijing,tabdiff,0.962145,0.862049,0.912097
3,beijing,catboost,0.775583,0.829211,0.802397

In [25]:
per_column_df

   Column  shape_score  dataset     model
0    year     0.973659  beijing   tabcsdi
1   month     0.894157  beijing   tabcsdi
2     day     0.857280  beijing   tabcsdi
3    hour     0.899425  beijing   tabcsdi
4   pm2.5     0.576389  beijing   tabcsdi
5    DEWP     0.494013  beijing   tabcsdi
6    TEMP     0.459052  beijing   tabcsdi
7    PRES     0.275623  beijing   tabcsdi
8    cbwd     0.774665  beijing   tabcsdi
9     Iws     0.428640  beijing   tabcsdi
10     Is     0.159243  beijing   tabcsdi
11     Ir     0.045738  beijing   tabcsdi
12   year     0.982759  beijing    tabsyn
13  month     0.944205  beijing    tabsyn
14    day     0.927443  beijing    tabsyn
15   hour     0.945402  beijing    tabsyn
16  pm2.5     0.950431  beijing    tabsyn
17   DEWP     0.988985  beijing    tabsyn
18   TEMP     0.981561  beijing    tabsyn
19   PRES     0.975814  beijing    tabsyn
20   cbwd     0.973898  beijing    tabsyn
21    Iws     0.855364  beijing    tabsyn
22     Is     0.996648  beijing    tabsyn
23     Ir     0.979406  beijing    tabsyn
24   year     0.978688  beijing   tabdiff
25  month     0.978448  beijing   tabdiff
26    day     0.944444  beijing   tabdiff
27   hour     0.963602  beijing   tabdiff
28  pm2.5     0.960967  beijing   tabdiff
29   DEWP     0.959052  beijing   tabdiff
30   TEMP     0.952107  beijing   tabdiff
31   PRES     0.954262  beijing   tabdiff
32   cbwd     0.990900  beijing   tabdiff
33    Iws     0.875239  beijing   tabdiff
34     Is     0.997605  beijing   tabdiff
35     Ir     0.990421  beijing   tabdiff
36   year     0.831897  beijing  catboost
37  month     0.953784  beijing  catboost
38    day     0.665709  beijing  catboost
39   hour     0.815374  beijing  catboost
40  pm2.5     0.841715  beijing  catboost
41   DEWP     0.963841  beijing  catboost
42   TEMP     0.959291  beijing  catboost
43   PRES     0.916906  beijing  catboost
44   cbwd     0.897270  beijing  catboost
45    Iws     0.729885  beijing  catboost
46     Is     0.309387  beijing  catboost
47     Ir     0.421935  beijing  catboost

In [26]:
pair_df

,Column 1,Column 2,Metric,Score,Real Correlation,Synthetic Correlation,Real Association,Meets Threshold?,dataset,model
0,year,month,ContingencySimilarity,NaN,NaN,NaN,0.054337,False,beijing,tabcsdi
1,year,day,ContingencySimilarity,NaN,NaN,NaN,0.083443,False,beijing,tabcsdi
2,year,hour,ContingencySimilarity,NaN,NaN,NaN,0.072217,False,beijing,tabcsdi
3,year,pm2.5,ContingencySimilarity,NaN,NaN,NaN,0.064373,False,beijing,tabcsdi
4,year,DEWP,ContingencySimilarity,NaN,NaN,NaN,0.085296,False,beijing,tabcsdi
...,...,...,...,...,...,...,...,...,...,...
259,cbwd,Is,ContingencySimilarity,NaN,NaN,NaN,0.032689,False,beijing,catboost
260,cbwd,Ir,ContingencySimilarity,NaN,NaN,NaN,0.052604,False,beijing,catboost
261,Iws,Is,CorrelationSimilarity,NaN,0.014429,NaN,NaN,False,beijing,catboost
262,Iws,Ir,CorrelationSimilarity,NaN,-0.028449,NaN,NaN,False,beijing,catboost
263,Is,Ir,CorrelationSimilarity,NaN,-0.008478,NaN,NaN,False,beijing,catboost